/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project3.parser;

import Project3.node.*;
import Project3.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTLparen(@SuppressWarnings("unused") TLparen node)
    {
        this.index = 0;
    }

    @Override
    public void caseTRparen(@SuppressWarnings("unused") TRparen node)
    {
        this.index = 1;
    }

    @Override
    public void caseTAssignment(@SuppressWarnings("unused") TAssignment node)
    {
        this.index = 2;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 3;
    }

    @Override
    public void caseTSemicolon(@SuppressWarnings("unused") TSemicolon node)
    {
        this.index = 4;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 5;
    }

    @Override
    public void caseTNumber(@SuppressWarnings("unused") TNumber node)
    {
        this.index = 6;
    }

    @Override
    public void caseTEcho(@SuppressWarnings("unused") TEcho node)
    {
        this.index = 7;
    }

    @Override
    public void caseTUnaryop(@SuppressWarnings("unused") TUnaryop node)
    {
        this.index = 8;
    }

    @Override
    public void caseTAddsub(@SuppressWarnings("unused") TAddsub node)
    {
        this.index = 9;
    }

    @Override
    public void caseTMuldivmod(@SuppressWarnings("unused") TMuldivmod node)
    {
        this.index = 10;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 11;
    }
}
