/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project3.analysis;

import Project3.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseATermExpression(ATermExpression node);
    void caseABinopexpExpression(ABinopexpExpression node);
    void caseAUnaryopexpExpression(AUnaryopexpExpression node);
    void caseASingleTerm(ASingleTerm node);
    void caseAMultipleTerm(AMultipleTerm node);
    void caseAIdValue(AIdValue node);
    void caseANumberValue(ANumberValue node);
    void caseAMultipleExplist(AMultipleExplist node);
    void caseASingleExplist(ASingleExplist node);
    void caseAAssignvalStmt(AAssignvalStmt node);
    void caseAPrintstmtStmt(APrintstmtStmt node);
    void caseAMultipleStmts(AMultipleStmts node);
    void caseASingleStmts(ASingleStmts node);

    void caseTLparen(TLparen node);
    void caseTRparen(TRparen node);
    void caseTAssignment(TAssignment node);
    void caseTComma(TComma node);
    void caseTSemicolon(TSemicolon node);
    void caseTId(TId node);
    void caseTNumber(TNumber node);
    void caseTEcho(TEcho node);
    void caseTUnaryop(TUnaryop node);
    void caseTAddsub(TAddsub node);
    void caseTMuldivmod(TMuldivmod node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
