/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project3.node;

import Project3.analysis.*;

@SuppressWarnings("nls")
public final class TEcho extends Token
{
    public TEcho()
    {
        super.setText("echo");
    }

    public TEcho(int line, int pos)
    {
        super.setText("echo");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEcho(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEcho(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEcho text.");
    }
}
