/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project3.analysis;

import Project3.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTEcho(TEcho node);
    void caseTLparen(TLparen node);
    void caseTRparen(TRparen node);
    void caseTAssignment(TAssignment node);
    void caseTComma(TComma node);
    void caseTSemicolon(TSemicolon node);
    void caseTId(TId node);
    void caseTNumber(TNumber node);
    void caseTUnaryop(TUnaryop node);
    void caseTAddsub(TAddsub node);
    void caseTMuldivmod(TMuldivmod node);
    void caseTEol(TEol node);
    void caseTBlank(TBlank node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
